title: Daniel Ku
logo: /assets/images/IMG_1909.jpg
description: <a href="https://www.linkedin.com/in/daniel-ku-879a32287/">LinkedIn</a>
description: <a href="mailto:ku.dan@northeastern.edu">Email Me</a>

# show_downloads: true
theme: jekyll-theme-dinky
