title: Daniel Ku
logo: /assets/images/IMG_1909.jpg
description:  
[LinkedIn](https://www.linkedin.com/in/daniel-ku-879a32287/) - LinkedIn
[Email](mailto:ku.dan@northeastern.edu) - Email

# show_downloads: true
theme: jekyll-theme-dinky
