title: Daniel Ku
logo: /assets/images/IMG_1909.jpg
description: <a href="https://www.linkedin.com/in/daniel-ku-879a32287/">LinkedIn</a>

Welcome to my portfolio page! I am currently a sophomore at Northeastern University!

# show_downloads: true
theme: jekyll-theme-dinky
